# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir httpx>=0.28.1 mcp[cli]>=1.9.4

# Copy server code
COPY mcpserver/ ./mcpserver

# Default command to run the MCP server over stdio
CMD ["python", "mcpserver/weather.py"]
